#ifndef COMMONSERVER_GLOBAL_H
#define COMMONSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMONSERVER_LIBRARY)
#  define COMMONSERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMONSERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMONSERVER_GLOBAL_H
